baseurl = "http://danvalencia.github.io/"
languageCode = "en-us"
title = "A Technology Journal"
theme = "detox"

[params]
  description = "Notes about technology and life."
  author = "Daniel Valencia"
