baseurl = "https://www.danvalencia.dev/"
languageCode = "en-us"
title = "A Technology Journal"
subtitle = "Notes about technology and life."
theme = "hello-friend-ng"

[author]
  name = "Daniel Valencia Backhoff"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Notes about technology and life."
  keywords = "homepage, blog, informatics, software development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "articles"

  # Default theme "light" or "dark"
  defaultTheme = "light"

# Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/_DanValencia"

  [[params.social]]
    name = "github"
    url  = "https://github.com/danvalencia"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/danvalencia"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/3254682/danvalencia"


[languages]
  [languages.en]
    title = "A Technology Journal"
    subtitle = "Notes about technology and life."
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = " cd ~"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "articles"
    name       = "Articles"
    url        = "/articles"

  [[menu.main]]
    identifier = "recipes"
    name       = "Recipes"
    url        = "/recipes"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/me"
    
[taxonomies]
  tag      = "tags"
  category = "categories"
